version: 3

tasks:
  lintall:
    desc: Lint all files
    cmds:
      - npm run lint
      - npm run prettier:check

  build:
    desc: Build the frontend
    cmds:
      - npm install
      - npm run build
      - npm run export
