version: '3'

dotenv: ['.vadikk.com.env']

includes:
  app:
    taskfile: ./app/taskfile.yaml
    dir: ./app

  frontend:
    taskfile: ./frontend/taskfile.yaml
    dir: ./frontend

  infra:
    taskfile: ./infra/taskfile.yaml
    dir: ./infra

tasks:
  'image:build':
    desc: Build the docker image
    env:
      BUILDKIT_PROGRESS: plain
    cmds:
      - docker build -t geography-data-mapper:latest -f Dockerfile .

  'image:run':
    desc: Run the docker image
    cmds:
      - docker run --rm -p 8000:8000 geography-data-mapper:latest

  'image:console':
    desc: Console into the docker image
    cmds:
      - docker run -it --rm -p 8000:8000 geography-data-mapper:latest sh

  build:
    desc: Build the app
    cmds:
      - task: frontend:build
      - task: image:build

  deploy:
    desc: Deploy the app
    cmds:
      - task: infra:deploy

  all:
    desc: Build and deploy the app
    cmds:
      - task: build
      - task: deploy