version: '3'

tasks:
  upload:
    desc: Upload the docker image to the remote machine using SSH
    cmds:
      - docker save geography-data-mapper:latest | ssh {{.UPLOAD_VIA}} 'docker load'

  scp:
    desc: desc copy env and docker-compose files to remote machine
    cmds:
      - ssh {{.UPLOAD_VIA}} 'mkdir -p /apps/geography-data-mapper'
      - ssh {{.UPLOAD_VIA}} 'touch /apps/geography-data-mapper/geomap.db'
      - scp .env {{.UPLOAD_VIA}}:/apps/geography-data-mapper/.env
      - scp docker-compose.yaml {{.UPLOAD_VIA}}:/apps/geography-data-mapper/docker-compose.yaml

  run:
    desc: Run the docker-compose file on the remote machine, restarting if it's already running
    cmds:
      - ssh {{.UPLOAD_VIA}} 'cd /apps/geography-data-mapper && docker-compose up -d --force-recreate'

  deploy:
    desc: Deploy the docker image to the remote machine
    cmds:
      - task: scp
      - task: upload
      - task: run

  pulldb:
    desc: Pull the database from the remote machine
    cmds:
      - scp {{.UPLOAD_VIA}}:/apps/geography-data-mapper/geomap.db ../dev-data/prod-geomap.db

  pushdb:
    desc: Push the database to the remote machine
    cmds:
      - scp ../dev-data/prod-geomap.db {{.UPLOAD_VIA}}:/apps/geography-data-mapper/geomap-new.db
      - ssh {{.UPLOAD_VIA}} 'cd /apps/geography-data-mapper && docker-compose stop'
      - ssh {{.UPLOAD_VIA}} 'mv /apps/geography-data-mapper/geomap.db /apps/geography-data-mapper/geomap.db.bak'
      - ssh {{.UPLOAD_VIA}} 'mv /apps/geography-data-mapper/geomap-new.db /apps/geography-data-mapper/geomap.db'
      - ssh {{.UPLOAD_VIA}} 'cd /apps/geography-data-mapper && docker-compose start'

  pushdevdb:
    desc: Push the development database to the remote machine
    cmds:
      - cp ../dev-data/db.sqlite ../dev-data/prod-geomap.db
      - task: pushdb